import '../models/tutorial_step.dart';
import 'tutorial_keys.dart';

List<TutorialStep> getTutorialSteps() {
  return [
    const TutorialStep(
      id: 'welcome',
      title: '欢迎使用',
      description: '欢迎使用 House Note！是否需要新手指引？',
      actionType: TutorialActionType.observe,
      requiresUserAction: false,
    ),
    const TutorialStep(
      id: 'template_tab_intro',
      title: '模板管理',
      description: '这里是模板管理页，你可以创建和管理看房维度模板。',
      actionType: TutorialActionType.observe,
      requiresUserAction: false,
    ),
    TutorialStep(
      id: 'create_first_template',
      title: '创建模板',
      description: '点击右下角按钮，创建你的第一个模板。',
      targetKey: TutorialKeys.templateListFab,
      actionType: TutorialActionType.tap,
    ),
    TutorialStep(
      id: 'enter_template_name',
      title: '输入模板名称',
      description: '输入模板名称。这里已经帮你填好了建议名称。',
      targetKey: TutorialKeys.templateNameField,
      actionType: TutorialActionType.type,
      defaultInput: '房子模板',
    ),
    TutorialStep(
      id: 'add_dimension',
      title: '添加维度项',
      description: '点击添加维度项，比如记录房子的朝向、楼层等信息。',
      targetKey: TutorialKeys.addDimensionButton,
      actionType: TutorialActionType.tap,
    ),
    const TutorialStep(
      id: 'configure_dimension',
      title: '配置维度',
      description: '输入名称「朝向」，选择类型「单选」，添加选项：东、南、西、北，然后保存。',
      actionType: TutorialActionType.type,
      defaultInput: '朝向',
    ),
    TutorialStep(
      id: 'add_more_dimensions',
      title: '继续添加维度',
      description: '继续添加「楼层」（数字类型）和「户型」（文本类型）。',
      targetKey: TutorialKeys.addDimensionButton,
      actionType: TutorialActionType.tap,
    ),
    const TutorialStep(
      id: 'set_thumbnail',
      title: '设置缩略图',
      description: '点击眼睛图标，设置缩略图显示字段。这些字段会显示在实例卡片上，方便对比。',
      actionType: TutorialActionType.observe,
      requiresUserAction: false,
    ),
    TutorialStep(
      id: 'save_template',
      title: '保存模板',
      description: '点击右上角保存模板。',
      targetKey: TutorialKeys.templateSaveButton,
      actionType: TutorialActionType.tap,
    ),
    TutorialStep(
      id: 'create_second_template',
      title: '创建小区模板',
      description: '再创建一个小区模板，并在其中引用房子模板，建立层级关系。',
      targetKey: TutorialKeys.templateListFab,
      actionType: TutorialActionType.tap,
    ),
    const TutorialStep(
      id: 'configure_community_template',
      title: '配置小区模板',
      description: '创建「小区模板」，添加「小区名」「位置」，再添加「引用子模板」维度，选择引用「房子模板」。',
      actionType: TutorialActionType.type,
      defaultInput: '小区模板',
    ),
    const TutorialStep(
      id: 'instance_tab_intro',
      title: '实例列表',
      description: '切换到首页，这里按层级展示你创建的看房实例。',
      actionType: TutorialActionType.observe,
      requiresUserAction: false,
    ),
    TutorialStep(
      id: 'create_instance',
      title: '创建实例',
      description: '点击创建第一个实例。选择「小区模板」。',
      targetKey: TutorialKeys.instanceListFab,
      actionType: TutorialActionType.tap,
    ),
    TutorialStep(
      id: 'enter_instance_details',
      title: '填写实例信息',
      description: '输入小区名称，比如「华润二十四城」，填入位置和通勤信息，然后保存。',
      targetKey: TutorialKeys.instanceSaveButton,
      actionType: TutorialActionType.type,
      defaultInput: '华润二十四城',
    ),
    const TutorialStep(
      id: 'navigate_into_instance',
      title: '进入实例',
      description: '点击实例卡片进入下一层。现在你可以在小区下创建房子实例了。',
      actionType: TutorialActionType.observe,
      requiresUserAction: false,
    ),
    TutorialStep(
      id: 'create_child_instance',
      title: '创建子实例',
      description: '点击创建子实例，选择「房子模板」，输入「7栋-1203」，填写朝向和楼层，保存。',
      targetKey: TutorialKeys.instanceListFab,
      actionType: TutorialActionType.type,
      defaultInput: '7栋-1203',
    ),
    const TutorialStep(
      id: 'swipe_delete_child',
      title: '删除子实例',
      description: '向左滑动实例卡片可以删除实例。',
      actionType: TutorialActionType.swipe,
    ),
    const TutorialStep(
      id: 'confirm_delete_child',
      title: '确认删除',
      description: '确认删除「7栋-1203」。因为这个实例下没有子实例，所以直接删除。',
      actionType: TutorialActionType.observe,
      requiresUserAction: false,
    ),
    TutorialStep(
      id: 'create_another_child',
      title: '再创建子实例',
      description: '我们再快速创建一个子实例，用来演示父实例的级联删除。',
      targetKey: TutorialKeys.instanceListFab,
      actionType: TutorialActionType.type,
      defaultInput: '8栋-1502',
    ),
    const TutorialStep(
      id: 'navigate_back',
      title: '返回上层',
      description: '点击面包屑导航的「全部」，回到上一层。',
      actionType: TutorialActionType.observe,
      requiresUserAction: false,
    ),
    const TutorialStep(
      id: 'swipe_delete_parent',
      title: '删除父实例',
      description: '向左滑动删除父实例。系统会提示将同时删除其下的子实例。',
      actionType: TutorialActionType.swipe,
    ),
    const TutorialStep(
      id: 'confirm_cascade_delete',
      title: '级联删除',
      description: '确认删除。可以看到提示「将同时删除 1 个子实例」，这就是级联删除。',
      actionType: TutorialActionType.observe,
      requiresUserAction: false,
    ),
    const TutorialStep(
      id: 'settings_tutorial',
      title: '教程完成',
      description: '教程完成！以后可以在「设置」→「查看教程」随时重新学习。',
      actionType: TutorialActionType.observe,
      requiresUserAction: false,
    ),
  ];
}
